id: P777D7278
initial_creation_type: ocr
source_metadata:
  volumes:
    747570876d154a539feefd666eaf11d3:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: འཕགས་པ་ལག་ན་རྡོ་རྗེ་གོས་སྔོན་པོ་ཅན་གྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག་ཐམས་ཅད་རྫོགས་པ།
      total_pages: 1853
      volume_number: 25
